// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cbind_combo
arma::sp_mat cbind_combo(const Rcpp::List& list_items);
RcppExport SEXP _mixgb_cbind_combo(SEXP list_itemsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type list_items(list_itemsSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind_combo(list_items));
    return rcpp_result_gen;
END_RCPP
}
// cbind_combo0
arma::sp_mat cbind_combo0(const Rcpp::List& list_items);
RcppExport SEXP _mixgb_cbind_combo0(SEXP list_itemsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type list_items(list_itemsSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind_combo0(list_items));
    return rcpp_result_gen;
END_RCPP
}
// cbind_sparse_matrix
arma::sp_mat cbind_sparse_matrix(const Rcpp::List& matrices_list);
RcppExport SEXP _mixgb_cbind_sparse_matrix(SEXP matrices_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type matrices_list(matrices_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cbind_sparse_matrix(matrices_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mixgb_cbind_combo", (DL_FUNC) &_mixgb_cbind_combo, 1},
    {"_mixgb_cbind_combo0", (DL_FUNC) &_mixgb_cbind_combo0, 1},
    {"_mixgb_cbind_sparse_matrix", (DL_FUNC) &_mixgb_cbind_sparse_matrix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mixgb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
